# Data Science Project 1: Data Wrangling Practical
**Duration:** 1 Hour, 15 Minutes  
**Format:** Open-notes code implementation (Python/Pandas)

### **Project Scenario**
You have been given a raw slice of **Glassdoor Data Science Job Postings**. The dataset contains a variety of small errors, missing variables, and split locations. Your goal is to clean this main dataset, create engineered features, and merge it with a regional mapping file so the analytics team can use it.

## Load the data
Download the data from the Blackboard to your computer frist, then load your libraries and the datasets required for this exam here.

In [84]:
# import all libaries and load your datasets your here
import numpy as np
import pandas as pd

glassdoor = pd.read_csv('glassdoor_jobs.csv')
states = pd.read_csv('state_regions.csv')

glassdoor.info()
states.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job_Title        672 non-null    str
 1   Job Description  672 non-null    str
 2   Rating           672 non-null    float64
 3   Company_Name     672 non-null    str
 4   Location         672 non-null    str
 5   Founded          672 non-null    int64
 6   Industry         618 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 2.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State_Abbreviation  9 non-null      str
 1   US_Region           9 non-null      str
dtypes: str(2)
memory usage: 346.0 bytes

## Part 1: Missing Data & Filtering (30 Points)

### **Task 1.1 (Standardizing Nulls)**
The `Rating` column represents missing values as `-1`. Replace all occurrences of `-1` with the dataset's overall **average (mean)** rating value.

In [85]:
# Write your solution for Task 1.1 here
mean_rating = glassdoor['Rating'].mean()

#fill -1 with 0s
glassdoor['Rating'] = glassdoor['Rating'].replace(-1,np.nan)


glassdoor['Rating'] = glassdoor['Rating'].fillna(mean_rating)
glassdoor.tail()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,2.984226,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
668,Data Scientist,Job Description\nBecome a thought leader withi...,2.984226,JKGT,"San Francisco, CA",-1,-1
669,Data Scientist,Join a thriving company that is changing the w...,2.984226,AccessHope,"Irwindale, CA",-1,-1
670,Data Scientist,100 Remote Opportunity As an AINLP Data Scient...,5.000000,ChaTeck Incorporated\n5.0,"San Francisco, CA",-1,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

### **Task 1.2 (Handling Blanks)**
The `Industry` column has several completely blank or empty cells. Fill these missing values with the string text `"Unknown"`.

In [86]:
# Write your solution for Task 1.2 here

glassdoor['Industry']= glassdoor['Industry'].replace("-1",np.nan)
glassdoor['Industry'].fillna("Unknown")
glassdoor.tail()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,2.984226,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
668,Data Scientist,Job Description\nBecome a thought leader withi...,2.984226,JKGT,"San Francisco, CA",-1,NaN
669,Data Scientist,Join a thriving company that is changing the w...,2.984226,AccessHope,"Irwindale, CA",-1,NaN
670,Data Scientist,100 Remote Opportunity As an AINLP Data Scient...,5.000000,ChaTeck Incorporated\n5.0,"San Francisco, CA",-1,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

### **Task 1.3 (Data Filtering)**
A few rows contain placeholder or invalid values in the `Founded` year column (values less than or equal to `0`). **Filter the dataset** to permanently remove these invalid rows.

In [87]:
# Write your solution for Task 1.3 here
glassdoor.dropna()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
...,...,...,...,...,...,...,...
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.800000,"Criterion Systems, Inc.\n3.8","Vienna, VA",2005,IT Services
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.000000,Foundation Medicine\n4.0,"Boston, MA",2010,Biotech & Pharmaceuticals
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,2.984226,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
670,Data Scientist,100 Remote Opportunity As an AINLP Data Scient...,5.000000,ChaTeck Incorporated\n5.0,"San Francisco, CA",-1,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

## Part 2: String Manipulations (20 Points)

### **Task 2.1 (Location Splitting)**
The `Location` column lists locations as `"City, State"` (e.g., `"Chicago, IL"` or `"Austin, TX"`). Split this column into two separate, brand-new columns: `Job_City` and `Job_State`.

In [88]:
# Write your solution for Task 2.1 here



glassdoor[['Job_City', 'Job_State']] = glassdoor['Location'].str.split(',',n=1, expand=True)


glassdoor.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing,New York,NY

### **Task 2.2 (Whitespace Cleaning)**
The new `Job_State` column might contain accidental leading or trailing empty spaces from the split. Apply a string cleaning function (like `.str.strip()`) to ensure no accidental spaces remain.

In [89]:
# Write your solution for Task 2.2 here
glassdoor['Job_State'] = glassdoor['Job_State'].str.strip()

## Part 3: Feature Engineering with Grouped Transformations (20 Points)

### **Task 3.1 (Grouped Transform)**
The recruiting team wants to identify jobs that offer a higher-than-average user rating relative to their specific field. 

Use `.groupby()` and `.transform()` to calculate the **average (mean) rating for each `Industry`**, broadcasting it back as a new column named `Industry_Avg_Rating`. Then, create a column called `Rating_Above_Industry_Avg` by subtracting `Industry_Avg_Rating` from the job's original `Rating`.

In [90]:
# Write your solution for Task 3.1 here

glassdoor['Industry_Avg_Rating'] = glassdoor.groupby('Industry')['Rating'].transform('mean')
glassdoor['Rating_Above_Industry_Avg'] = glassdoor['Rating'] - glassdoor['Industry_Avg_Rating']


glassdoor.head()

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers,New York,NY,3.549599,-0.449599
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA",1968,Research & Development,Chantilly,VA,3.791778,0.408222
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,2.984226,Analysis Group\n3.8,"Boston, MA",1981,Consulting,Boston,MA,3.630872,-0.646646
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing,Newton,MA,3.242113,0.257887
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing,New York,NY,3.602509,-0.702509

## Part 4: Merging & Aggregating Data (30 Points)

### **Task 4.1 (Dataset Merging)**
You are provided a second, clean reference CSV file named `state_regions.csv` which contains two columns: `State_Abbreviation` and `US_Region` (e.g., *IL, Midwest*). 

Perform a **left merge** to add the `US_Region` column to your main job postings dataframe by matching your new `Job_State` column with the reference file's `State_Abbreviation` column.

In [92]:
# Write your solution for Task 4.1 here
glassdoor_merge = glassdoor.merge(states[['State_Abbreviation','US_Region']], left_on = "Job_State", right_on ='State_Abbreviation',how='left')

### **Task 4.2 (Grouped Aggregation)**
Group your newly merged dataframe by the `US_Region` column. For each region, calculate:
1. The **total count** of job postings in that region.
2. The **average (mean)** employee `Rating` in that region.

In [ ]:
# Write your solution for Task 4.2 here

### **Task 4.3 (Data Export)**
Save your final, aggregated summary table from Task 4.2 to a new file named `regional_job_summary.csv`.

In [ ]:
# Write your solution for Task 4.3 here